apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow-app

  process:
    matchPaths:
      - path: /bin/bash
      - path: /usr/bin/nc
      - path: /usr/games/fortune
      - path: /usr/games/cowsay
      - path: /bin/cat
      - path: /bin/echo
      - path: /bin/sleep
      - path: /bin/rm
      - path: /usr/bin/mkfifo

  file:
    matchDirectories:
      - dir: /
        recursive: true

  network:
    matchProtocols:
      - protocol: tcp
        fromSource:
          - path: /usr/bin/nc

  action: Allow
